In [1]:
import numpy as np
import gurobipy as gp

## 1. Pie Eating Contest

In [2]:
q1Mod=gp.Model()
q1ModX = q1Mod.addMVar(2) 

Set parameter Username
Academic license - for non-commercial use only - expires 2024-08-20


In [3]:
q1Mod.setObjective(4*q1ModX[0] + 5*q1ModX[1],sense=gp.GRB.MAXIMIZE)

In [4]:
conlist1=[0]*2

conlist1[0] = q1Mod.addConstr(2*q1ModX[0] + 3*q1ModX[1] <= 60)

In [5]:
q1Mod.Params.OutputFlag = 0 
q1Mod.optimize()

In [6]:
q1Mod.objVal

120.0

In [7]:
q1ModX.x

array([30.,  0.])

In [8]:
conlist1[1] = q1Mod.addConstr(q1ModX[0] <= q1ModX[1])

In [9]:
q1Mod.optimize()

In [10]:
q1Mod.objVal

108.0

In [11]:
q1ModX.x

array([12., 12.])

## 2. Farmer in Iowa

In [12]:
q2Mod=gp.Model()
q2ModX = q2Mod.addMVar(2) 

In [13]:
q2Mod.setObjective(2000*q2ModX[0] + 3000*q2ModX[1],sense=gp.GRB.MAXIMIZE)

In [14]:
conlist2=[0]*3

conlist2[0] = q2Mod.addConstr(3*q2ModX[0] + 2*q2ModX[1] <= 1000)
conlist2[1] = q2Mod.addConstr(2*q2ModX[0] + 4*q2ModX[1] <= 1200)
conlist2[2] = q2Mod.addConstr(q2ModX[0] + q2ModX[1] <= 450)

In [15]:
q2Mod.Params.OutputFlag = 0 
q2Mod.optimize()

In [16]:
q2Mod.objVal

1000000.0

In [17]:
q2ModX.x

array([200., 200.])

In [18]:
farmer_dict = {}

for keys in range(200, 2201, 100):
    q2Mod=gp.Model()
    q2ModX = q2Mod.addMVar(2) 
    q2Mod.setObjective(2000*q2ModX[0] + 3000*q2ModX[1],sense=gp.GRB.MAXIMIZE)
    conlist3=[0]*3
    conlist3[0] = q2Mod.addConstr(3*q2ModX[0] + 2*q2ModX[1] <= 1000)
    conlist3[1] = q2Mod.addConstr(2*q2ModX[0] + 4*q2ModX[1] <= keys)
    conlist3[2] = q2Mod.addConstr(q2ModX[0] + q2ModX[1] <= 450)
    q2Mod.Params.OutputFlag = 0 
    q2Mod.optimize()
    farmer_dict[keys] = q2ModX.x 
    
    if q2ModX[0].x ==0:
        print(keys)
        break

1800


In [19]:
print(farmer_dict)

{200: array([100.,   0.]), 300: array([150.,   0.]), 400: array([200.,   0.]), 500: array([250.,   0.]), 600: array([300.,   0.]), 700: array([325. ,  12.5]), 800: array([300.,  50.]), 900: array([275. ,  87.5]), 1000: array([250., 125.]), 1100: array([225. , 162.5]), 1200: array([200., 200.]), 1300: array([175. , 237.5]), 1400: array([150., 275.]), 1500: array([125. , 312.5]), 1600: array([100., 350.]), 1700: array([ 50., 400.]), 1800: array([  0., 450.])}


## 3. Star Oil Company

In [20]:
q3Mod=gp.Model()
q3ModX = q3Mod.addMVar(5, lb=0, ub=1)

In [21]:
q3Mod.setObjective(13*q3ModX[0] + 16*q3ModX[1]+ 16*q3ModX[2] + 14*q3ModX[3] +39*q3ModX[4],sense=gp.GRB.MAXIMIZE)

In [22]:
conlist4=[0]*2

conlist4[0] = q3Mod.addConstr(11*q3ModX[0] + 53*q3ModX[1]+ 5*q3ModX[2] + 5*q3ModX[3] +29*q3ModX[4] <= 40)
conlist4[1] = q3Mod.addConstr(3*q3ModX[0] + 6*q3ModX[1]+ 5*q3ModX[2] + 1*q3ModX[3] +34*q3ModX[4] <= 20)


In [23]:
q3Mod.Params.OutputFlag = 0 
q3Mod.optimize()

In [24]:
q3Mod.objVal

57.449017199017206

In [25]:
q3ModX[2].x

array(1.)

## 4. Daily Nutritional Requirement

In [26]:
q4Mod=gp.Model()
q4ModX = q4Mod.addMVar(3, lb=0, ub=10)

In [27]:
q4Mod.setObjective(0.18*q4ModX[0] + 0.23*q4ModX[1] + 0.05*q4ModX[1],sense=gp.GRB.MINIMIZE)

In [28]:
conlist5=[0]*4

conlist5[0] = q4Mod.addConstr(107*q4ModX[0] + 500*q4ModX[1] <= 50000)
conlist5[1] = q4Mod.addConstr(107*q4ModX[0] + 500*q4ModX[1] >= 500)
conlist5[2] = q4Mod.addConstr(72*q4ModX[0] + 121*q4ModX[1] + 65*q4ModX[2] <= 2250)
conlist5[3] = q4Mod.addConstr(72*q4ModX[0] + 121*q4ModX[1] + 65*q4ModX[2] >= 2000)


In [29]:
q4Mod.Params.OutputFlag = 0 
q4Mod.optimize()

In [30]:
q4Mod.objVal

3.1500000000000004

In [31]:
q4ModX[0].x

array(1.94444444)

## 5. Forest and Wood

In [32]:
q5Mod=gp.Model()
q5ModX = q5Mod.addMVar((2,3))

In [33]:
q5Mod.setObjective(q5ModX[0,0] + 1.3*q5ModX[0,1] + 1.4 * q5ModX[0,2] + q5ModX[1,0] + 1.2 *q5ModX[1,1] + 1.6*q5ModX[1,2],sense=gp.GRB.MAXIMIZE)

In [34]:
conlist6=[0]*8

conlist6[0] = q5Mod.addConstr(q5ModX[0,0] + q5ModX[1,0] <= 2)
conlist6[1] = q5Mod.addConstr(q5ModX[0,0] + q5ModX[1,0] >= 1.2)

conlist6[2] = q5Mod.addConstr(1.3 * q5ModX[0,1] + 1.2 * q5ModX[1,1] <= 2)
conlist6[3] = q5Mod.addConstr(1.3 * q5ModX[0,1] + 1.2 * q5ModX[1,1] >= 1.5)

conlist6[4] = q5Mod.addConstr(1.4 * q5ModX[0,2] + 1.6 * q5ModX[1,2] <= 3)
conlist6[5] = q5Mod.addConstr(1.4 * q5ModX[0,2] + 1.6 * q5ModX[1,2] >= 2)

conlist6[6] = q5Mod.addConstr(q5ModX[0,0] + q5ModX[0,1] + q5ModX[0,2] <= 2)
conlist6[7] = q5Mod.addConstr(q5ModX[1,0] + q5ModX[1,1] + q5ModX[1,2] <= 3)


In [35]:
q5Mod.optimize()

Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (mac64[arm])

CPU model: Apple M2
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 8 rows, 6 columns and 18 nonzeros
Model fingerprint: 0xeff48103
Coefficient statistics:
  Matrix range     [1e+00, 2e+00]
  Objective range  [1e+00, 2e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 3e+00]
Presolve removed 3 rows and 0 columns
Presolve time: 0.00s
Presolved: 5 rows, 9 columns, 15 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    7.0000000e+00   2.660587e+00   0.000000e+00      0s
       4    6.5865385e+00   0.000000e+00   0.000000e+00      0s

Solved in 4 iterations and 0.00 seconds (0.00 work units)
Optimal objective  6.586538462e+00


In [36]:
q5Mod.objVal

6.586538461538462

In [37]:
q5ModX.x

array([[0.46153846, 1.53846154, 0.        ],
       [1.125     , 0.        , 1.875     ]])