In [1]:
#!pip install gurobipy

In [2]:
import numpy as np
import gurobipy as gp

## Problem 1

In [3]:
m1 = gp.Model()
x = m1.addMVar(6,lb=[-6,-5,0,0,6,0])

obj = [2,-2,3,3,4,-1]
m1.setObjective(gp.quicksum(x[i]*obj[i] for i in range(6)),sense=gp.GRB.MAXIMIZE)
lessCons = m1.addConstrs(x[i] <= x[j] for i in range(5) for j in range(i+1,6))
# lessCons = m1.addConstrs(x[i] <= x[i+1] for i in range(5)) # this would also work.. if w < x < y, you automatically know w < y also..
sumCon = m1.addConstr(gp.quicksum(x[i] for i in range(6))<= 10)
m1.Params.OutputFlag=0
m1.optimize()
print(x.x)
print(m1.objval)

Set parameter Username
Academic license - for non-commercial use only - expires 2024-08-20
[-6.  -5.   4.5  4.5  6.   6. ]
43.0


In [4]:
np.sum([-6. , -5. ,  4.5 , 4.5 , 6.  , 6. ])

10.0

In [5]:
np.sum([-6., -5. , 3. , 6. , 6. , 6.])

10.0

In [6]:
sumCon.Pi

array(3.)

In [7]:
sumCon.SARHSLow

array(1.)

In [8]:
sumCon.SARHSUp

array(13.)

In [9]:
x.SAObjLow

array([-inf, -inf,   3.,   1., -inf, -inf])

In [10]:
x.SAObjUp

array([ 3.,  3., inf,  3.,  7.,  2.])

In [11]:
15*40*2

1200

## Problem 2

In [12]:
ip = gp.Model()
hire = ip.addMVar(6,vtype='B')
time = ip.addMVar((6,2))
M = 40
bigMcons = ip.addConstrs(time[i,0]+time[i,1] <= M*hire[i] for i in range(6))
salesPrice = [10,15]
goodsPhour = [[10,15,12,10,9,8],[9,8,9,15,15,12]]
salary = [700,800,1000,900,800,750]

ip.setObjective(gp.quicksum(time[i,j]*goodsPhour[j][i]*salesPrice[j] for i in range(6) for j in range(2)) - gp.quicksum(hire[i]*salary[i] for i in range(6)),sense=gp.GRB.MAXIMIZE)
ip.addConstr(gp.quicksum(salary[i]*hire[i] for i in range(6)) <= 4000)
ip.addConstr(gp.quicksum(hire[i] for i in range(6)) <= 4)
ip.addConstr(gp.quicksum(time[i,0]*goodsPhour[0][i] for i in range(6)) >= 650)

ip.addConstr(hire[0] <= hire[5])


ip.Params.OutputFlag=0
ip.optimize()
hire.x

array([0., 1., 0., 1., 1., 1.])

In [13]:

time.x

array([[ 0.,  0.],
       [40.,  0.],
       [ 0.,  0.],
       [ 5., 35.],
       [ 0., 40.],
       [ 0., 40.]])

In [14]:
ip.objval

27325.0

In [15]:
ip.Params.OutputFlag=0
ip.optimize()
hire.x

array([0., 1., 0., 1., 1., 1.])